# Generated by Django 5.2.4 on 2025-07-31 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_required', models.CharField(choices=[('borehole-drilling', 'Borehole Drilling'), ('water-treatment', 'Water Treatment'), ('hydrogeological-survey', 'Hydrogeological Survey'), ('site-investigation', 'Site Investigation'), ('environmental-assessment', 'Environmental Assessment'), ('geological-mapping', 'Geological Mapping')], max_length=50)),
                ('project_description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('timeline', models.CharField(blank=True, max_length=200)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
