# Generated by Django 5.2.4 on 2025-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
